### ISSUE TITLE
Want a script that installs everything automatically on a headless Centos on the cloud like Scaleway

### ISSUE THREAD

**Issue by pythonwebcoder** [ArkCase/arkcase-ce#23]

**Comment by david-oc-miller** [comment]
Ubuntu is unsupported; it has to be CentOS 7.6 or CentOS 7.7.  With either of these CentOS systems, the ansible scripts in this repository will install from scratch.  But you have to provide the minimal CentOS installation.

**Comment by pythonwebcoder** [comment]
@david-oc-miller changed the title to be Centos now double checking Scaleway has Centos

**Comment by pythonwebcoder** [comment]
OK I created a Centos instance with 32gb of ram on Scaleway now making a script

**Comment by david-oc-miller** [comment]
I see the readme isn't totally clear on how to stand up ArkCase on a cloud site, versus on a local VM.

The installer configuration is split into a playbook recipe file, which says what Ansible plays will be run; and a metadata file, which contains all the configuration information.  The default script is as follows:

`ansible-playbook -i 'arkcase-ce.local,' -e @arkcase-ce-facts.yml arkcase-ce.yml`

Which you would run from the vagrant/provisioning folder.  arkcase-ce-facts.yml is the facts file.  Definitely you need to read this file and possibly make some updates, especially in the email configuration which is set to a non-functional email account by default.  

`arkcase-ce.local` in the above command is the local host name.  You would run the script like so:

`ansible-playbook -e @arkcase-ce-facts.yml arkcase-ce.yml`

But first you would edit the arkcase-ce-facts.yml.

**Comment by pythonwebcoder** [comment]
I'm having troubles logging into Centos on scaleway. My schedule doesn't allow me to retry again until Monday.

**Comment by david-oc-miller** [comment]
New Year's ticket review: closing due to length of time since last update.
