### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by dpieski** [ArkCase/arkcase-ce#264]
> Examine the file centos7.json. This file sets the new VM to have 8G RAM (do not lessen this value, but you can make it higher if you want) and 128G disk space (again, you can choose higher value, but do not choose a lower one).

It looks like the VM is set to have 6GB RAM though? 

``` json 
"vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--memory",
          "6144"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--cpus",
          "2"
        ]
      ]
```

**Comment by david-oc-miller** [comment]
Fixed here: https://github.com/ArkCase/arkcase-ce/pull/361
