### ISSUE TITLE
Getting error while adding LDAP server

### ISSUE THREAD

**Issue by phulethanh1993** [ArkCase/arkcase-ce#322]
I'm new in LDAP.
I'm trying to add LDAP server (Keycloak) to Arkcase app following this document:
https://www.arkcase.com/security/
I copied all the input fields from the default LDAP server, except ID, LDAP Url, Base, Auth User DN, Auth User Password, and Users Search Base (These fields are from Keycloak).
At the front end, I got a Success message, but when I checked arkcase log I found an error
```
org.springframework.ldap.OperationNotSupportedException: [LDAP: error code 12 - Unavailable Critical Extension]; nested exception is 
javax.naming.OperationNotSupportedException: [LDAP: error code 12 - Unavailable Critical Extension]; remaining name '<text that I entered at Base input field>'
```
I tried changing the Base input field, but I get this error all the time.
Has anyone encountered this issue? please tell me how to solve it

**Comment by davidmiller-sharecare** [comment]
@phulethanh1993 ,

When you added the LDAP configuration, did you choose Active Directory as the directory type, or OpenLDAP (or whichever is the alternative to Active Directory)?

Can you attach the rest of your stack trace?  I'm guessing that the missing critical extension is "Server Side Paging", and I'm hoping that if you chose Active Directory before, by switching to the other option, maybe things will work.

**Comment by david-oc-miller** [comment]
@phulethanh1993, are you still interested in ArkCase?  Did you get any good results from changing the directory type from Active Directory to OpenLDAP, or perhaps from OpenLDAP to Active Directory?

**Comment by david-oc-miller** [comment]
Closing this issue now.  Please reopen, or create a new issue as needed.
