### ISSUE TITLE
404 Error While Connecting to WebApp

### ISSUE THREAD

**Issue by MultiTrickFox** [ArkCase/arkcase-ce#325]
Hello, I have performed all steps regarding the installation/boot of the VM, As well as the modification of hots.txt
The error while connecting to WebApp via https://arkcase-ce.local/arkcase, is a simple TomCat 404 error. Could you help me on this? Thank you..

**Comment by MultiTrickFox** [comment]
Edit: Trying the exact same also results in 502 Proxy Error. There is no failure with VM startup or executing. I have no idea why the webapp is not getting connected

**Comment by david-oc-miller** [comment]
@MultiTrickFox , it takes some time for ArkCase to start the first time... it may be working by now.

If you still get 502, or 503 or some other error, can you please ssh into the VM (e.g. by running the command `vagrant ssh`, and then run this command: `wget --no-check-certificate https://localhost:8843/arkcase`.  If this returns an HTML file like normal then ArkCase is running inside the VM.  If you get an error I'll ask you to look into the ArkCase log.

Thanks for trying ArkCase.
