### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by mikmolefe** [ArkCase/arkcase-ce#372]
I get the following error
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Also 

**sudo systemctl status config-server says**
● config-server.service - ArkCase Config Server
   Loaded: loaded (/etc/systemd/system/config-server.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: timeout) since Fri 2022-01-14 15:45:38 GMT; 2s ago
  Process: 15851 ExecStart=/usr/bin/java -Dserver.port=9999 -Djava.net.preferIPv4Stack=true -jar /opt/app/config-server/config-server.jar (code=exited, status=143)

Jan 14 15:45:38 arkcase-ce.local systemd[1]: Failed to start ArkCase Config Server.
Jan 14 15:45:38 arkcase-ce.local systemd[1]: Unit config-server.service entered failed state.
Jan 14 15:45:38 arkcase-ce.local systemd[1]: config-server.service failed.

but

**sudo systemctl status arkcase is oK**

**Comment by david-oc-miller** [comment]
@mikmolefe ,

Yes, the ArkCase web app will not deploy without the config server.  

I haven't seen `status=143` from config-server before.  Can you send me some more information?

- Output of the command `git status` in your arkcase-ce folder
- Did you deploy on CentOS 7, or on RHEL 8?
- From the Vagrant VM, output of the command `sudo journalctl -xe -u config-server`
- From the Vagrant VM, the config server log file, it should be in the folder `/opt/arkcase/log/config-server`

Thanks,
Dave

**Comment by david-oc-miller** [comment]
@mikmolefe ,

I spoke too soon, `status=143` is the expected exit code when running config server; this is how Spring Boot is supposed to work.  Still, if you send me the information as requested above, we'll figure out what's happening.

--
Dave

**Comment by mikmolefe** [comment]
I am running a VM form https://app.vagrantup.com/arkcase/boxes/arkcase-ce/versions/3.3.
Here is output of journalctl -xe -u config-server
[config-server-log.txt](https://github.com/ArkCase/arkcase-ce/files/7874477/config-server-log.txt)

Thanks

**Comment by david-oc-miller** [comment]
@mikmolefe ,

3.3 is a pretty old version.  From this page, which version exactly have you chosen?  e.g. 3.3.0, or 3.3.1?  We don't have a version that is exactly 3.3.

I believe the config server SystemD unit file has some issue.  Can you send me the file `/etc/systemd/system/config-server.service`?

As an alternative, you could follow the instructions here, https://github.com/ArkCase/arkcase-ce#how-to-create-the-base-centos-image-and-install-arkcase-yourself,  to create a new VM from scratch, using the most recent ArkCase version, 2021.03.

We stopped pushing new Vagrant images some time ago, but we will start again soon.

--
Dave

**Comment by david-oc-miller** [comment]
@mikmolefe , are you good to go now?

**Comment by mikmolefe** [comment]
I tried 2021.03 and it is working. Now trying in LXD container, SELinux has issues in containers.

Thanks man.
