### ISSUE TITLE
vagrant up fails with Windows 10 1909 and VirtualBox 6.0.10

### ISSUE THREAD

**Issue by jdshinnick** [ArkCase/arkcase-ce#45]
Using the provided Vagrant image, when running vagrant up, I get an error:
Stderr: VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter' (VERR_INTNET_FLT_IF_NO T_FOUND).

After some looking around, saw instructions on disabling and re-enabling the network adapters associated with the "VirtualBox Host-Only Ethernet Adapter" and "VirtualBox Host-Only Ethernet Adapter # 2" on my laptop. 

This got me past the issue of the above error. I had not seen this earlier after Windows 10 1809 and 1903 updates. 

Recommend adding to the Wiki page to save others some frustration.

**Comment by ordwinbryan** [comment]
how do you do this

> Using the provided Vagrant image, when running vagrant up, I get an error: Stderr: VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter' (VERR_INTNET_FLT_IF_NO T_FOUND).
> 
> After some looking around, saw instructions on disabling and re-enabling the network adapters associated with the "VirtualBox Host-Only Ethernet Adapter" and "VirtualBox Host-Only Ethernet Adapter # 2" on my laptop.
> 
> This got me past the issue of the above error. I had not seen this earlier after Windows 10 1809 and 1903 updates.
> 
> Recommend adding to the Wiki page to save others some frustration.

How do you do this.. still new to this

**Comment by david-oc-miller** [comment]
@ordwinbryan do you see this same error message, `Stderr: VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter' (VERR_INTNET_FLT_IF_NO T_FOUND).`?  Which version of the Vagrant image do you have?  What is your version of Windows?  What is your version of VirtualBox?

Thanks,
Dave

**Comment by david-oc-miller** [comment]
@ordwinbryan this is a generic VirtualBox-on-Windows issue.  If you search the error message online, you will see a number of possible solutions.

I am closing this issue now.  Please reopen, or create a new issue as needed.
