### ISSUE TITLE
any chance of getting the pdftron libraries for the CE version?

### ISSUE THREAD

**Issue by cnnganga** [ArkCase/arkcase-ce#558]

**Comment by srinivasagunturu** [comment]
Hi @cnnganga ,

Thank you for contacting ArkCase Support, We will take a look into your issue and get back to you shortly.

**Comment by srinivasagunturu** [comment]
Hi @cnnganga ,

Please let me know what version of Arkcase you are using.

**Comment by cnnganga** [comment]
Hi,

the version of arkcase is 2021.03

rgds.

Charles

**Comment by srinivasagunturu** [comment]
Hi @cnnganga ,

Please give us some time to check this with our internal team and get back to you.

**Comment by srinivasagunturu** [comment]
Hi @cnnganga,

Pdftron libraries are currently not configured with the CE version.

**Comment by cnnganga** [comment]
Noted, thanks
