### ISSUE TITLE
New Document Task on Consultation Does not pick Parent Object

### ISSUE THREAD

**Issue by cnnganga** [ArkCase/arkcase-ce#559]
When you upload a document on a consultation and right click on it to create a new document task against that document the system does not pick the parent object i.e. parent consultation and number hence the task can not be created. See attached.

![image](https://github.com/ArkCase/arkcase-ce/assets/83939204/b446980c-c7a4-4e56-a1de-049d72ab5f20)

**Comment by srinivasagunturu** [comment]
Hi @cnnganga,

Thank you for contacting ArkCase Support, we will take a look into your issue and get back to you shortly.

**Comment by srinivasagunturu** [comment]
Hi @cnnganga ,

Please tell me which version of Arkcase you are using.
I request that you review the parent types that you can see in the admin module.
Please follow the path shown in the attached screenshot.



![559](https://github.com/ArkCase/arkcase-ce/assets/110920447/e4286d81-bbb5-43db-82eb-bf1ffb34b45f)

**Comment by cnnganga** [comment]
Hi,

thanks for your response, my version of arkcase is 2021.03, the adhoc tasks against the consultation works as with all other objects. The one not working is the document task as shown below:

![image](https://github.com/ArkCase/arkcase-ce/assets/83939204/4bc875cf-db06-4674-b02b-cf21e2450ee3)

**Comment by srinivasagunturu** [comment]
Hi @cnnganga ,

Because the parent object is not required for this adhoc task, please fill out all mandatory details and click the save task button.

Please let me know what error you are seeing when you try to save the task.

**Comment by cnnganga** [comment]
Nope, all good. Thankyou.

**Comment by cnnganga** [comment]
Thank You Again.

**Comment by cnnganga** [comment]
Hi Sorry, I realized the task is not an adhoc task but an ACM Document Workflow task, hence its not working

**Comment by cnnganga** [comment]
Please combine this issue with issue #560 as below:

IF I change 'Set Primary' variable under lookups It does pick the primary type as consultation but I have to search for the actual object... see below:

![image](https://github.com/ArkCase/arkcase-ce/assets/83939204/cd3cfc9d-6620-4ca8-aeac-eb6c2d82dcc8)

![image](https://github.com/ArkCase/arkcase-ce/assets/83939204/4f96fe16-6d09-45ac-8e64-0b54023a8400)

**Comment by srinivasagunturu** [comment]
Hi @cnnganga ,
As discussed during the call, the parent object type and parent object id for the consultant object will not be populated by design.
Let me check this internally and open an improvement ticket.
As a workaround, you can create the task using the global "+new" button, or you can add those details by making the set primary for consultant in the parent type lookup.
