### ISSUE TITLE
The URL for community Edition has type error - https://arcase-ce.local/arkcase

### ISSUE THREAD

**Issue by kamal-0916** [ArkCase/arkcase-ce#72]
Now you should be able to open the web site **https://arcase-ce.local/arkcase** in your browser. You will have to accept the ArkCase HTTPS certificate; your browser will show you a warning since ArkCase CE uses its own root certificate.

The higlighted url has typo error. It should have 'k'.
**https://arkcase-ce.local/arkcase**
I spent couple of hours and was not able to access the application even after following all the documented steps.

**Comment by david-oc-miller** [comment]
Fixed in this commit: https://github.com/ArkCase/arkcase-ce/commit/b4250bf0a38316dd0630cd639c0d3831f9fdacdc#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
